name: 'Get current package version'
description: 'Get the current version of the npm package'
branding:
  color: 'gray-dark'
  icon: 'align-center'
inputs:
  path:
    required: false
    default: '.'
    description: 'Path to package.json file (directories only), e.g. packages/mypackage/'
outputs:
  current-version:
    description: 'Current version defined in the package.json file'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/npm-get-version-action:v1.3.3@sha256:3666f9fdf5e99e3a48f1f2755b4ea33d529cdf6566a95ec0c0eba52bc10fba36' #v1.3.3
  args:
    - ${{ inputs.path }}
