name: 'Get current package version'
description: 'Get the current version of the npm package'
branding:
  color: 'gray-dark'
  icon: 'align-center'
inputs:
  path:
    required: false
    default: '.'
    description: 'Path to package.json file (directories only), e.g. packages/mypackage/'
outputs:
  current-version:
    description: 'Current version defined in the package.json file'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/npm-get-version-action:v1.3.5@sha256:36be375e40ea776c5b23d48a91feb80e53eb1da80ff4a33b5f54c553943fb37d' #v1.3.5
  args:
    - ${{ inputs.path }}
