name: 'Get current package version'
description: 'Get the current version of the npm package'
branding:
  color: 'gray-dark'
  icon: 'align-center'
inputs:
  path:
    required: false
    default: '.'
    description: 'Path to package.json file (directories only), e.g. packages/mypackage/'
outputs:
  current-version:
    description: 'Current version defined in the package.json file'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/npm-get-version-action:v1.3.2@sha256:9f92683d1b262d7b56e58484a6792768207fcb8a7c25dd6cf6ea1e43ded6ddd0' #v1.3.2
  args:
    - ${{ inputs.path }}
